### PR TITLE
SK0 116

### PR DESCRIPTION
**Pull request by markkovari**
- **chore: add route, component and actions**
- **chore(SK0-116): add action reducers, types and service method**
- **test(SK0-116): reducer action unit test**
- **test(SK0-116): add effect test for auth service calls**
- **test(SK0-116): tests effects for navigation of action**
- **fix(SK0-116): do not filter numbers**

### CODE REVIEW

**Review by rolcho — APPROVED** [review]
Looking good, I think I have found some bugs and missing tests in the code, other than that look nice!  🚀  😎 
[SK0-116-update](https://github.com/cimem-hu/sk0/pull/102)

**Comment by markkovari** [comment]
@rolcho thanks, the past week was a bit lower effort for me, really appreciate contribution, next time feel free to just push to the branch if you agree, even branches should be matter of cooperations. 💪

**Comment by markkovari** [comment]
uuuh, nice catches sonar, good bot, will update those today

**Comment by rolcho** [comment]
> uuuh, nice catches sonar, good bot, will update those today

🐶  🦴  😄 

The only thing I don't understand that the bot was not complaining about touch-like events until last week or before?!
If it is a problem I will walk through the codebase because there is no event handling for it in any other case where we use buttons or button like operations.

**Comment by markkovari** [comment]
It started like 2 weeks ago, but I suppressed them, there was no option to add it to the ion-button. So I just dismissed it.

**Comment by rolcho** [comment]
Bing says: 
```html
<ion-button (click)="navigateHome()" (keydown)="handleKeyDown($event)" (keypress)="handleKeyPress($event)" (keyup)="handleKeyUp($event)" class="ion-margin-top">
Vissza a kezdőoldalra
</ion-button>
```

In this example, ```handleKeyDown```, ```handleKeyPress```, and ```handleKeyUp``` are methods you would define in your component to handle the keyboard events. The specifics of these methods would depend on what you want to happen when the user interacts with the button using the keyboard.

**Review by rolcho — APPROVED** [review]

**Pull request merged**
