### PR TITLE
Chore/add ngrx for login

### PR DESCRIPTION
**Pull request by markkovari**

### CODE REVIEW

**Review by rolcho — APPROVED** [review]
nice and elegant

**Review by Thomas851204 — APPROVED** [review]
I apologize to approve without comment, but it will take some time to even understand whats happening here...

**Comment by markkovari** [comment]
@Thomas851204 no worries, then we should delay merging it 👍 we should avoid merging this until it is useable by everyone

**Comment by markkovari** [comment]
Actually everyone should understand THEN approve it first.

**Comment by markkovari** [comment]
and @Thomas851204 don't apologise when asking for clarity 💯

**Pull request closed without merging**
